keys:
  age:
    - &marisa age1sfnct03u4cvfj98x4yjrcrrnu5gg8qgxrwk4uqq8w4e6wveeaedq97rn44
    - &flandre age15fqerwsfnwsdqdwr4egw2ng73e8qqzrqh23qrhtleauuvvryzvvquvzzrw
creation_rules:
  - path_regex: nixos/marisa.*
    key_groups:
      - age:
          - *marisa
  - path_regex: nixos/flandre.*
    key_groups:
      - age:
          - *marisa
          - *flandre
