[dnsmasq-china-list]
src.git = "https://github.com/felixonmars/dnsmasq-china-list"
fetch.github = "felixonmars/dnsmasq-china-list"

[chnroutes2]
src.git = "https://github.com/misakaio/chnroutes2"
fetch.github = "misakaio/chnroutes2"

[metacubexd]
src.github_tag = "MetaCubeX/metacubexd"
fetch.url = "https://github.com/MetaCubeX/metacubexd/releases/download/$ver/compressed-dist.tgz"

[bird-babel-rtt]
src.git = "https://github.com/tohojo/bird"
src.branch = "babel-rtt-01"
fetch.github = "tohojo/bird"
