[dnsmasq-china-list]
src.git = "https://github.com/felixonmars/dnsmasq-china-list"
fetch.github = "felixonmars/dnsmasq-china-list"

[telegram-desktop-megumifox]
src.git = "https://github.com/archlinuxcn/repo"
fetch.url = "https://raw.githubusercontent.com/archlinuxcn/repo/$ver/archlinuxcn/telegram-desktop-megumifox/0001-Use-font-from-environment-variables.patch"

[chnroutes2]
src.git = "https://github.com/misakaio/chnroutes2"
fetch.github = "misakaio/chnroutes2"

[metacubexd]
src.github_tag = "MetaCubeX/metacubexd"
fetch.url = "https://github.com/MetaCubeX/metacubexd/releases/download/$ver/compressed-dist.tgz"
