# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chnroutes2 = {
    pname = "chnroutes2";
    version = "59752fd7f9438a8305ece944e71ba45b9b57775e";
    src = fetchFromGitHub {
      owner = "misakaio";
      repo = "chnroutes2";
      rev = "59752fd7f9438a8305ece944e71ba45b9b57775e";
      fetchSubmodules = false;
      sha256 = "sha256-yZN7b7dhYu2qX9WHNWUY8xpSuilYdDJ4sp16aCV+XDY=";
    };
    date = "2024-04-25";
  };
  dnsmasq-china-list = {
    pname = "dnsmasq-china-list";
    version = "3713f09710000af0a78d0b467f6817365976058c";
    src = fetchFromGitHub {
      owner = "felixonmars";
      repo = "dnsmasq-china-list";
      rev = "3713f09710000af0a78d0b467f6817365976058c";
      fetchSubmodules = false;
      sha256 = "sha256-BrvNgnUIHPqHe4HK0SLy/1Ya9tqAc2RcfU9sGUjScbg=";
    };
    date = "2024-04-25";
  };
  metacubexd = {
    pname = "metacubexd";
    version = "v1.138.1";
    src = fetchurl {
      url = "https://github.com/MetaCubeX/metacubexd/releases/download/v1.138.1/compressed-dist.tgz";
      sha256 = "sha256-l2mcb2optvgtfzma/Ix63Y8BxXC6CsGoyIIMoOvD074=";
    };
  };
  telegram-desktop-megumifox = {
    pname = "telegram-desktop-megumifox";
    version = "e5a6a3e1e0d837f86d7ffdd69dbcc00c217950ac";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/archlinuxcn/repo/e5a6a3e1e0d837f86d7ffdd69dbcc00c217950ac/archlinuxcn/telegram-desktop-megumifox/0001-Use-font-from-environment-variables.patch";
      sha256 = "sha256-IQiyJPbFZ0XSSZbcMYS0J1dej5G5LRx4qB/frW7QtnA=";
    };
    date = "2024-04-25";
  };
}
