# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chnroutes2 = {
    pname = "chnroutes2";
    version = "0823f40de93dbcf13f707fb9ea6b1b2c6c9897ac";
    src = fetchFromGitHub {
      owner = "misakaio";
      repo = "chnroutes2";
      rev = "0823f40de93dbcf13f707fb9ea6b1b2c6c9897ac";
      fetchSubmodules = false;
      sha256 = "sha256-zd+sOzxdrdhjddWxsnKsWVE+6IuAG39Qe8AarotzFWk=";
    };
    date = "2024-04-30";
  };
  dnsmasq-china-list = {
    pname = "dnsmasq-china-list";
    version = "2476df3067ebf518e35097c44bf6f623e95da59a";
    src = fetchFromGitHub {
      owner = "felixonmars";
      repo = "dnsmasq-china-list";
      rev = "2476df3067ebf518e35097c44bf6f623e95da59a";
      fetchSubmodules = false;
      sha256 = "sha256-CUuPjzC/O0XOM0H0CanYzbC95DjpMR7WeeFZ3NLkLls=";
    };
    date = "2024-04-30";
  };
  metacubexd = {
    pname = "metacubexd";
    version = "v1.138.1";
    src = fetchurl {
      url = "https://github.com/MetaCubeX/metacubexd/releases/download/v1.138.1/compressed-dist.tgz";
      sha256 = "sha256-l2mcb2optvgtfzma/Ix63Y8BxXC6CsGoyIIMoOvD074=";
    };
  };
  telegram-desktop-megumifox = {
    pname = "telegram-desktop-megumifox";
    version = "9f037216b0f0fc44515503374b3278219a2c71cf";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/archlinuxcn/repo/9f037216b0f0fc44515503374b3278219a2c71cf/archlinuxcn/telegram-desktop-megumifox/0001-Use-font-from-environment-variables.patch";
      sha256 = "sha256-IQiyJPbFZ0XSSZbcMYS0J1dej5G5LRx4qB/frW7QtnA=";
    };
    date = "2024-05-01";
  };
}
