# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chnroutes2 = {
    pname = "chnroutes2";
    version = "ca84c3057acc9404e07e949c30d69ce16ee596a5";
    src = fetchFromGitHub {
      owner = "misakaio";
      repo = "chnroutes2";
      rev = "ca84c3057acc9404e07e949c30d69ce16ee596a5";
      fetchSubmodules = false;
      sha256 = "sha256-y/CuwAhgtAKaZ3frUvhpUvnv80psubHkMJ1LsQEoiiY=";
    };
    date = "2024-04-15";
  };
  dnsmasq-china-list = {
    pname = "dnsmasq-china-list";
    version = "f0c5854b46bfe2eda06000fb5d75038108c35d51";
    src = fetchFromGitHub {
      owner = "felixonmars";
      repo = "dnsmasq-china-list";
      rev = "f0c5854b46bfe2eda06000fb5d75038108c35d51";
      fetchSubmodules = false;
      sha256 = "sha256-aoka2JlwLp4i8L3FGVJmQlaI7j9ZWjCSfIqr/qVr+V4=";
    };
    date = "2024-04-15";
  };
  metacubexd = {
    pname = "metacubexd";
    version = "v1.138.0";
    src = fetchurl {
      url = "https://github.com/MetaCubeX/metacubexd/releases/download/v1.138.0/compressed-dist.tgz";
      sha256 = "sha256-0cy+HSZzVY4vVNbFu/MRUQtKjCo2Ebg4bq2H9kHjFG4=";
    };
  };
  telegram-desktop-megumifox = {
    pname = "telegram-desktop-megumifox";
    version = "a83809b8f39f64cb852606dbbf0717655cd274ed";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/archlinuxcn/repo/a83809b8f39f64cb852606dbbf0717655cd274ed/archlinuxcn/telegram-desktop-megumifox/0001-Use-font-from-environment-variables.patch";
      sha256 = "sha256-IQiyJPbFZ0XSSZbcMYS0J1dej5G5LRx4qB/frW7QtnA=";
    };
    date = "2024-04-16";
  };
}
